export const UI_CONSTANTS = {
  HOUR_HEIGHT_MOBILE: 42,
  HOUR_HEIGHT_DESKTOP: 64,
  MOBILE_BREAKPOINT: 600,
  EVENT_TITLE_MAX_LENGTH: 40,
  EVENT_PLACE_MAX_LENGTH: 20,
  EVENT_TITLE_DISPLAY_LENGTH: 20,
  SEARCH_MIN_LENGTH: 2,
  SEARCH_RESULTS_LIMIT: 5,
  SEARCH_DEBOUNCE_MS: 400,
  API_TIMEOUT_MS: 7000,
  TOAST_DURATION_MS: 3000,
  NOTIFICATION_CHECK_INTERVAL_MS: 60000,
  FORM_GAP: '12px',
  AUTH_BUTTON_HEIGHT_DESKTOP: 59,
  AUTH_BUTTON_HEIGHT_MOBILE: 42,
  DEFAULT_EVENT_COLOR: '#ffcb33',
  DEFAULT_LOCATION: 'spb'
} as const;

export const BREAKPOINTS = {
  mobile: 480,
  tablet: 768,
  desktop: 1024,
  large: 1200
} as const;

export const ANIMATION_DURATION = {
  fast: '0.15s',
  normal: '0.2s',
  slow: '0.3s'
} as const;